### ISSUE TITLE
kedro_telemetry error

### ISSUE THREAD

**Issue by jacobweiss2305** [quantumblacklabs/kedro-docker#60]
## Description
Kedro docker run fails with kedro telemetry error message

## Context
How has this bug affected you? What were you trying to accomplish?

I could not complete a kedro run. 

## Steps to Reproduce

1. `kedro new --starter=spaceflights`
2. `pip install kedro-docker`
3. `cd project directory`
4. `kedro-docker init`
5. `kedro docker build`
6. `kedro docker run` (point of failure)

## Expected Result
Complete kedro run without errors.

## Actual Result
I get the same error after successful install of kedro-telemetry

```
As an open-source project, we collect usage analytics.
We cannot see nor store information contained in a Kedro project.
You can find out more by reading our privacy notice:
https://github.com/quantumblacklabs/kedro-telemetry#privacy-notice
Do you opt into usage analytics?  [y/N]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/click/termui.py", line 200, in confirm
    value = visible_prompt_func("").lower().strip()
EOFError: EOF when reading a line

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 265, in main
    cli_collection()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 206, in main
    self._cli_hook_manager.hook.before_command_run(
  File "/usr/local/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/local/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/site-packages/kedro_telemetry/plugin.py", line 70, in before_command_run
    consent = _check_for_telemetry_consent(project_metadata.project_path)
  File "/usr/local/lib/python3.8/site-packages/kedro_telemetry/plugin.py", line 166, in _check_for_telemetry_consent
    return _confirm_consent(telemetry_file_path)
  File "/usr/local/lib/python3.8/site-packages/kedro_telemetry/plugin.py", line 190, in _confirm_consent
    if click.confirm(confirm_msg):
  File "/usr/local/lib/python3.8/site-packages/click/termui.py", line 202, in confirm
    raise Abort()
```

## Your Environment
Include as many relevant details about the environment you experienced the bug in:

* Kedro-Docker plugin version used (get it by running `pip show kedro-docker`): 0.2.2
* Docker version (`docker --version`): 20.10.7
* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.4
* Python version used (`python -V`): 3.8.9
* Operating system and version: Windows 10

**Comment by jacobweiss2305** [comment]
I was able to get a successful run by using kedro docker run --image "spaceflights:latest".

**Comment by stevenhoelscher** [comment]
I ran into this issue as well and the solution of specifying the `--image` flag didn't change the behavior for me.

To avoid user prompt from `kedro-telemetry` I simply removed it from the `src/requirements.txt`
