### ISSUE TITLE
Kedro docker e2e tests fail with "ImportError cannot import name 'get_installed_distributions"

### ISSUE THREAD

**Issue by AhdraMeraliQB** [quantumblacklabs/kedro-docker#63]
## Description
Kedro install fails when e2e tests are run due to problems with pip and pip-tools. Related issues have highlighted a similar problem in https://github.com/quantumblacklabs/kedro/issues/994 and https://github.com/jazzband/pip-tools/issues/1503.

## Context
How has this bug affected you? What were you trying to accomplish?
Failing tests on CI builds block further development.

## Steps to Reproduce

1. Clone the repository
2. Checkout develop branch: `git checkout develop`
3. Run end-to-end tests in terminal: `make e2e-tests`

## Expected Result
Tests should pass.

## Actual Result
Tests do not pass.

```
And I have executed the kedro command "install"                                                              # features/steps/cli_steps.py:162 1.556s
      Traceback (most recent call last):
        File "/home/circleci/miniconda/envs/kedro-docker/lib/python3.6/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/circleci/miniconda/envs/kedro-docker/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/cli_steps.py", line 172, in exec_make_target_checked
          assert False
      AssertionError
      
      Captured stdout:
      DeprecationWarning: Command `kedro install` will be deprecated in Kedro 0.18.0. In the future use `pip install -r src/requirements.txt` instead. If you were running `kedro install` with the `--build-reqs` flag, we recommend running `kedro build-reqs` followed by `pip install -r src/requirements.txt`
      No requirements.in found. Copying contents from requirements.txt...
      /tmp/tmp5v3zehry/bin/python -m piptools compile -q /tmp/tmpi9v936bt/project-dummy/src/requirements.in
      
      Traceback (most recent call last):
        File "/home/circleci/miniconda/envs/kedro-docker/lib/python3.6/runpy.py", line 193, in _run_module_as_main
          "__main__", mod_spec)
        File "/home/circleci/miniconda/envs/kedro-docker/lib/python3.6/runpy.py", line 85, in _run_code
          exec(code, run_globals)
        File "/tmp/tmp5v3zehry/lib/python3.6/site-packages/piptools/__main__.py", line 3, in <module>
          from piptools.scripts import compile, sync
        File "/tmp/tmp5v3zehry/lib/python3.6/site-packages/piptools/scripts/sync.py", line 10, in <module>
          from pip._internal.utils.misc import get_installed_distributions
      ImportError: cannot import name 'get_installed_distributions'
      /tmp/tmp5v3zehry/lib/python3.6/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
        import imp
```

## Your Environment
Include as many relevant details about the environment you experienced the bug in:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.5
* Python version used (`python -V`): 3.7.11
* Operating system and version: MacOS 11.5.2
* Pip version used: 21.3.1
* Pip-tools version used: 5.5.0

**Comment by AhdraMeraliQB** [comment]
Resolved in #64
